### PR TITLE
Pathlib import

### PR DESCRIPTION
**Pull request by Darkheir**
Same as before but also with the support of new methods and keyword arguments.

### CODE REVIEW

**Comment by netromdk** [comment]
Thanks a lot for the additions! Could you please rebase from master and have a look at the warnings, like
```
tests/function.py:1121:1: W293 blank line contains whitespace
```
and others.

**Comment by netromdk** [comment]
Hi again, @Darkheir. If you could interactively rebase your new changes to remove the duplicate commits, and then rebase onto master so that you don't have the commits about adding support for `pathlib` which is already in master.

**Comment by netromdk** [comment]
There are very few warnings left: https://travis-ci.org/netromdk/vermin/jobs/404432236#L631

**Comment by Darkheir** [comment]
My bad I didn't seen where the code formatting rules were.

Maybe it could be useful to set a config file (`setup.cfg`,` tox.ini`, or `.flake8`) for flake8 instead of having it hardcoded in the `Makefile`

**Pull request merged**
